### ISSUE TITLE
Q: Why does the example for Maybe.cata and Result.cata divide the input height by 2.2?

### ISSUE THREAD

**Issue by khtan** [rametta/pratica#32]
Hi team,

There is an example that is repeated in Maybe.cata, Result.cata where the input height is divided by 2.2 [ map(h => h /2.2 ) ]. However there is no obvious reason to do the division, except to further reduce the height. The examples will still work without this scaling and clearer as a learning example.

https://github.com/rametta/pratica#maybecata
https://github.com/rametta/pratica#resultcata

Hope someone can add some comments to the code or simplify it. 

Thanks,

**Comment by rametta** [comment]
@khtan Do you have any suggestion on how to make it more clear?

**Comment by khtan** [comment]
Hi Rametta,  sorry for not responding in time. Hope you can still read my comment and respond.

This is the original code:
```
isOver6Feet({ height: 4.5 })
  .map(h => h / 2.2)
  .cata({
    Just: h => console.log(h), // this function doesn't run
    Nothing: () => console.log(`person is not over 6 feet`)
  })
```
**Suggestion 1:**
Use 2 examples, one with height 4.5, the other with height 7.5 to show the
2 branches of the code, and following the pattern of your original comments

```
isOver6Feet({ height: 4.5 })
  .cata({
    Just: h => console.log(h), // this function doesn't run
    Nothing: () => console.log(`person is not over 6 feet`)
  })
isOver6Feet({ height: 7.5 })
  .cata({
    Just: h => console.log(h), // prints 7.5
    Nothing: () => console.log(`person is not over 6 feet`) // this function doesn't run
  })
```

**Suggestion 2:**
Take out the map(h => h /2.2 ) because it does not add to the understanding how Maybe is used.
   In fact it raises more questions like
   a. Is 2.2 an arbitrary constant or a conversion factor
   b. Since the height is in feet, is 2.2 a conversion from imperial to metric
   etc

**Comment by rametta** [comment]
@khtan perhaps you can open a PR with your suggestion? Would be very helpful!

**Comment by khtan** [comment]
Thank you for your encouragement. I was about to do so when I saw that you
have updated the readme code with helpful comments. This completely
addresses my questions, so there is no need for me to add a PR.
Thanks for a very useful and indispensable functional programming library.
