### ISSUE TITLE
Publish as Deno Module

### ISSUE THREAD

**Issue by jannes** [rametta/pratica#36]
would be cool to publish this as a Deno module as well besides NPM
https://deno.land/manual@v1.30.0/advanced/publishing

It looks like it should be easy

**Comment by rametta** [comment]
@jannes good idea. Do you have experience publishing deno pkgs? If yes, would you be able to open a PR to add this?

**Comment by jannes** [comment]
hey, I just started using Deno, so I haven't published anything yet. Also, I actually switched to using [neverthrow](https://github.com/supermacro/neverthrow) instead of pratica, so I'm not invested in this feature request anymore. 

Feel free to close this again, however, I do think it may be worth the effort ;)
