### ISSUE TITLE
shouldn't chain be called flatMap?

### ISSUE THREAD

**Issue by talJoffeExelate** [rametta/pratica#6]
The ability to do flat is one of the characteristics of a Monad.
If a Monad is mapped to a Monad we can use flat to work with the Monad and not have Monad of Monad (like you are doing with chain).

Is .chain used to make it more native to Javascript? (like promise)
Because flatMap is also pretty common I think

**Comment by rametta** [comment]
The choice to use chain was because I am following mostly the fantasy land spec and chain is used in the spec, so it made more sense. https://github.com/fantasyland/fantasy-land#chain
